"""All Facebook-group DOM knowledge lives here and ONLY here.

Two things live in this module:

1. Injected JavaScript (`EXPAND_SEE_MORE_JS`, `EXTRACT_POSTS_JS`,
   `COUNT_POSTS_JS`, `DUMP_ARTICLES_JS`) that runs inside the page via
   Playwright's ``page.evaluate`` and returns *raw* post objects (plain
   strings/arrays, no normalization).
2. Python-side normalization (`normalize_raw_post`) that turns a raw object
   into the project's canonical schema using helpers from ``utils``.

Design rules (from the spec):
- Prefer semantic HTML, aria-labels, roles, anchors, permalink patterns and
  relative DOM relationships. Avoid autogenerated CSS class names.
- Every selector/heuristic carries a semantic comment explaining what it
  identifies.
- Use multiple strategies for important fields; take the first reliable result.

The selectors below were verified against the live logged-in group DOM. Facebook
serves (at least) two structures and this parser handles both:

* **Comet feed** (current `www.facebook.com` render): posts are direct children
  of a ``[role="feed"]`` container, the body is
  ``[data-ad-rendering-role="story_message"]``, there is NO ``role="article"``
  wrapper and NO clean ``/posts/`` permalink anchor — the post id is recovered
  from ``set=pcb.<id>`` photo links, ``story_fbid``, or ``multi_permalinks``.
* **Legacy article** render: each post is a top-level ``div[role="article"]``
  with a ``/groups/<id>/posts/<id>`` permalink in the timestamp anchor.
"""

from __future__ import annotations

from typing import Any

from . import utils

# The canonical empty record. Every collected post is a copy of this with
# fields filled in only when reliably extracted; unknowns stay ``None``.
EMPTY_POST: dict[str, Any] = {
    "post_id": None,
    "post_url": None,
    "group_url": None,
    "timestamp_text": None,
    "timestamp": None,
    "text": None,
    "reaction_count": None,
    "comment_count": None,
    "share_count": None,
    "image_urls": [],
    "video_urls": [],
    "crawl_time": None,
}


# ---------------------------------------------------------------------------
# Shared JS snippet: locate post containers for BOTH DOM variants.
# ---------------------------------------------------------------------------
# Defined once and prepended to each injected function so the boundary logic
# stays identical everywhere.
_CONTAINERS_JS = r"""
  // Return the list of post-container elements, comet feed first.
  function postContainers() {
    const out = [];
    const feed = document.querySelector('[role="feed"]');
    if (feed) {
      for (const k of feed.children) {
        // A real post child holds a story message (or the older preview body).
        if (k.querySelector('[data-ad-rendering-role="story_message"], '
              + '[data-ad-preview="message"], [data-ad-comet-preview="message"]')) {
          out.push(k);
        }
      }
      if (out.length) return out;
    }
    // Legacy fallback: top-level role=article posts (skip comments/skeletons).
    for (const a of document.querySelectorAll('div[role="article"]')) {
      const label = (a.getAttribute('aria-label') || '').toLowerCase();
      if (label.startsWith('comment') || label.includes('bình luận')) continue;
      if (label.startsWith('loading')) continue;
      if (a.querySelector('[role="status"][data-visualcompletion="loading-state"]')) continue;
      const parentArticle = a.parentElement
        ? a.parentElement.closest('div[role="article"]') : null;
      if (parentArticle) continue;  // nested article -> skip
      out.push(a);
    }
    return out;
  }
"""


# ---------------------------------------------------------------------------
# Injected JS: expand every "See more" affordance in the feed.
# ---------------------------------------------------------------------------
EXPAND_SEE_MORE_JS = r"""
() => {
  const LABELS = ['See more', 'See More', 'Xem thêm', 'Hiển thị thêm'];
  let clicked = 0;
  // "See more" is a role=button element inside a post body.
  for (const el of document.querySelectorAll('div[role="button"], span[role="button"]')) {
    const t = (el.textContent || '').trim();
    if (LABELS.includes(t)) {
      try { el.click(); clicked++; } catch (e) { /* ignore */ }
    }
  }
  return clicked;
}
"""


# ---------------------------------------------------------------------------
# Injected JS: count rendered (non-skeleton) posts. Used to wait for the feed.
# ---------------------------------------------------------------------------
COUNT_POSTS_JS = r"""
() => {
""" + _CONTAINERS_JS + r"""
  return postContainers().length;
}
"""


# ---------------------------------------------------------------------------
# Injected JS: extract raw post objects from both DOM variants.
# ---------------------------------------------------------------------------
EXTRACT_POSTS_JS = r"""
() => {
""" + _CONTAINERS_JS + r"""

  // Group identifier: numeric id OR vanity name (e.g. /groups/nhatrohngiare).
  // Must accept both, else permalinks can't be built for vanity-named groups.
  const groupId = (location.href.match(/\/groups\/([^/?#]+)/) || [])[1] || null;
  const abs = (h) => { try { return new URL(h, location.origin).href; } catch (e) { return h; } };
  const hasDigit = (s) => !!s && /\d/.test(s);

  // Relative-time patterns (EN + VI) used to identify the timestamp anchor.
  const TIME_RE = /^(just now|vừa xong|yesterday|hôm qua|\d+\s*(m|h|d|w|y|s|giờ|phút|ngày|tuần|năm|giây)|\d{1,2}\s+\w+)/i;
  const COMMENT_RE = /(\d[\d.,]*\s*[KMBkmb]?)\s*(comments?|bình luận)/i;
  const SHARE_RE   = /(\d[\d.,]*\s*[KMBkmb]?)\s*(shares?|(?:lượt\s*)?chia sẻ)/i;

  const results = [];
  for (const k of postContainers()) {
    const raw = {
      post_url: null, post_id: null, timestamp_text: null, text: null,
      reaction_text: null, comment_text: null, share_text: null,
      image_urls: [], video_urls: [],
    };

    // -- Post text --
    // Primary: the post body container. Fallback: largest dir="auto" block.
    let textEl = k.querySelector(
      '[data-ad-rendering-role="story_message"], '
      + '[data-ad-preview="message"], [data-ad-comet-preview="message"]'
    );
    if (!textEl) {
      let best = null, bestLen = 0;
      for (const el of k.querySelectorAll('div[dir="auto"]')) {
        const len = ((el.innerText || el.textContent) || '').trim().length;
        if (len > bestLen) { best = el; bestLen = len; }
      }
      textEl = best;
    }
    if (textEl) {
      // innerText keeps visual line breaks in real browsers; textContent is
      // the fallback. Replace non-breaking spaces with normal spaces.
      const txt = (textEl.innerText || textEl.textContent || '');
      raw.text = txt.replace(/ /g, ' ').trim() || null;
    }

    // -- Permalink / post id (multi-strategy, first reliable wins) --
    const hrefs = Array.from(k.querySelectorAll('a[href]')).map(a => a.getAttribute('href') || '');
    let pid = null;
    for (const h of hrefs) {
      let m;
      if ((m = h.match(/\/groups\/\d+\/posts\/(\d+)/)) ||       // A: clean post permalink
          (m = h.match(/\/groups\/\d+\/permalink\/(\d+)/)) ||   // B: permalink form
          (m = h.match(/set=pcb\.(\d+)/)) ||                     // C: comet photo bundle id
          (m = h.match(/[?&]story_fbid=(\d+)/)) ||               // D: story_fbid
          (m = h.match(/multi_permalinks=(\d+)/))) {             // E: multi_permalinks
        pid = m[1]; break;
      }
    }
    if (pid) {
      raw.post_id = pid;
      raw.post_url = groupId ? (location.origin + '/groups/' + groupId + '/posts/' + pid) : null;
    }
    // If a direct posts/permalink anchor exists, prefer its canonical href.
    if (!raw.post_url) {
      const pa = hrefs.find(h => /\/groups\/\d+\/(posts|permalink)\/\d+/.test(h));
      if (pa) raw.post_url = abs(pa);
    }

    // -- Timestamp text --
    // The timestamp is an anchor whose visible text (or aria-label) is a
    // relative time. We must NOT pick the author link (href has "/user/").
    for (const a of k.querySelectorAll('a[role="link"], a[href]')) {
      if ((a.getAttribute('href') || '').includes('/user/')) continue;  // author, skip
      const t = (a.textContent || '').trim();
      if (t && t.length < 25 && TIME_RE.test(t)) { raw.timestamp_text = t; break; }
      const al = a.getAttribute('aria-label') || '';
      if (!raw.timestamp_text && al && al.length < 28 && TIME_RE.test(al)) {
        raw.timestamp_text = al;
      }
    }

    // -- Reaction count --
    // A summary aria-label carrying a digit and a reaction/like phrase, e.g.
    // "Like: 12 people", "12 reactions", "See who reacted, 12 people".
    for (const el of k.querySelectorAll('[aria-label]')) {
      const l = el.getAttribute('aria-label') || '';
      if (!hasDigit(l)) continue;
      if (/reaction|reacted|\bpeople\b|cảm xúc|like\s*:/i.test(l)) { raw.reaction_text = l; break; }
    }

    // -- Comment / share counts --
    // Require a digit ADJACENT to the localized noun; this ignores the bare
    // action buttons ("Comment"/"Share") and bare numbers we can't attribute.
    for (const el of k.querySelectorAll('[role="button"], a[href], span, div')) {
      const t = (el.textContent || '').trim();
      if (!t || t.length > 40 || !hasDigit(t)) continue;
      if (raw.comment_text == null && COMMENT_RE.test(t)) raw.comment_text = t;
      if (raw.share_text == null && SHARE_RE.test(t)) raw.share_text = t;
    }

    // -- Media --
    // Post photos come from scontent.*.fbcdn.net. Reject UI sprites, emoji,
    // stickers (static/rsrc), profile pictures, and small icons.
    const seenImg = new Set();
    for (const img of k.querySelectorAll('img')) {
      const src = img.currentSrc || img.src || '';
      if (!src || src.startsWith('data:')) continue;
      if (/\/rsrc\.php|emoji|sticker|static\.(?:[a-z0-9-]+\.)?fbcdn/.test(src)) continue;
      if (!/scontent/.test(src)) continue;  // only real content images
      const w = img.naturalWidth || img.width || 0;
      const h = img.naturalHeight || img.height || 0;
      if (w && h && (w < 120 || h < 120)) continue;  // icon/avatar
      if (img.closest('a[href*="/user/"], a[href*="/profile.php"]')) continue;  // avatar
      if (!seenImg.has(src)) { seenImg.add(src); raw.image_urls.push(src); }
    }
    const seenVid = new Set();
    for (const v of k.querySelectorAll('video')) {
      let src = v.currentSrc || v.src || '';
      if (!src) { const s = v.querySelector('source'); if (s) src = s.src || ''; }
      if (src && !src.startsWith('blob:') && !seenVid.has(src)) {
        seenVid.add(src); raw.video_urls.push(src);
      }
    }

    // Emit only usable candidates (has a permalink OR text).
    if (raw.post_url || raw.text) results.push(raw);
  }
  return results;
}
"""


# ---------------------------------------------------------------------------
# Injected JS: prune already-scrolled posts to bound memory on long crawls.
# ---------------------------------------------------------------------------
# A single tab scrolling through thousands of image-heavy posts exhausts the
# renderer's memory and Chrome kills the tab ("Target crashed"). Images are the
# dominant cost. We must NOT remove feed nodes — that breaks Facebook's
# infinite-scroll loader (it stops fetching new posts once the DOM is disturbed).
# Instead we keep every node (so scroll/observers stay intact) and blank the
# MEDIA of already-scrolled posts (all but the most recent `keep`): clearing an
# <img> src releases its decoded bitmap. We've already saved these posts, so the
# stripped URLs are not lost. Returns the number of media elements blanked.
PRUNE_FEED_JS = r"""
(keep) => {
  const feed = document.querySelector('[role="feed"]');
  if (!feed) return 0;
  const kids = feed.children;
  const limit = kids.length - keep;
  let blanked = 0;
  for (let i = 0; i < limit; i++) {
    for (const img of kids[i].querySelectorAll('img')) {
      if (img.src || img.srcset) {
        img.removeAttribute('srcset');
        img.src = 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==';
        blanked++;
      }
    }
    for (const v of kids[i].querySelectorAll('video')) {
      try { v.removeAttribute('src'); v.load && v.load(); blanked++; } catch (e) { /* ignore */ }
    }
  }
  return blanked;
}
"""


# ---------------------------------------------------------------------------
# Injected JS: dump outer HTML of the first N post containers (offline debug).
# ---------------------------------------------------------------------------
DUMP_ARTICLES_JS = r"""
(n) => {
""" + _CONTAINERS_JS + r"""
  return postContainers().slice(0, n).map(el => el.outerHTML);
}
"""


# ---------------------------------------------------------------------------
# Python-side normalization
# ---------------------------------------------------------------------------


def normalize_raw_post(raw: dict, group_url: str, crawl_time: str) -> dict:
    """Turn one raw JS post object into the canonical schema.

    Applies URL/text/count normalization via ``utils``. ``post_id`` prefers a
    value parsed from the permalink, else the id the extractor recovered
    (e.g. from a comet ``pcb`` photo link). Unknown fields stay ``None`` (or
    ``[]`` for media). Never invents values.
    """
    record = {**EMPTY_POST, "image_urls": [], "video_urls": []}
    record["group_url"] = group_url
    record["crawl_time"] = crawl_time

    post_url = utils.normalize_url(raw.get("post_url"))
    record["post_url"] = post_url
    record["post_id"] = (
        utils.extract_post_id(raw.get("post_url"))
        or (utils.extract_post_id(post_url) if post_url else None)
        or (str(raw["post_id"]) if raw.get("post_id") else None)
    )

    record["timestamp_text"] = raw.get("timestamp_text") or None
    ts = raw.get("timestamp_text")
    if ts and _looks_iso(ts):
        record["timestamp"] = ts

    record["text"] = utils.normalize_text(raw.get("text"))

    record["reaction_count"] = utils.parse_count(raw.get("reaction_text"))
    record["comment_count"] = utils.parse_count(raw.get("comment_text"))
    record["share_count"] = utils.parse_count(raw.get("share_text"))

    record["image_urls"] = _dedup_keep_order(raw.get("image_urls") or [])
    record["video_urls"] = _dedup_keep_order(raw.get("video_urls") or [])

    return record


def _looks_iso(value: str) -> bool:
    """Heuristic: does this timestamp text look like an ISO 8601 datetime?"""
    value = value.strip()
    return len(value) >= 10 and value[4:5] == "-" and value[7:8] == "-"


def _dedup_keep_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item and item not in seen:
            seen.add(item)
            out.append(item)
    return out
